CLASS LHC_ZZIR_TEST_R_EMPLOYEEEMP DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZzirTestREmployeeemp
        RESULT result.
ENDCLASS.

CLASS LHC_ZZIR_TEST_R_EMPLOYEEEMP IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
